## Tensor
1. 텐서란?
- 데이터의 배열, 배열의 집합이다.
- 차원의 수는 Rank와 같은 말이다.
- 배열의 차원에 따라 불리는 이름이 달라진다.

2. 0차원 텐서
- 하나의 실수값으로 이루어진 데이터, 스칼라
- 0D 텐서

3. 1차원 텐서
- 숫자를 특정 순서대로 배열한 것, 벡터
- 1D 텐서

4. 2차원 텐서
- 행과 열이 존재하는 벡터의 배열, 행렬
- 2D 텐서

5. 3차원 텐서
- 0~2차원 텐서는 각각 스칼라, 벡터, 행렬이라고 해도 무방하다.
- 3차원 이상의 텐서부터 본격적으로 텐서라고 부른다.
- 3D 텐서
- 시퀀스 데이터를 표현할 때 자주 이용 --> 자연어 처리
- (samples(batch_size), timesteps, word_dim) 
- samples/batch_size: 데이터 개수, timesteps: 시퀀스 길이(문장 길이), word_dim: 단어를 표현하는 벡터의 차원

## 시퀀스
### 시퀀스란
- 데이터에 순서(번호)를 붙여 나열한 것
- 아이스크림, 커피, 설탕, 쿠키, 우유 ==> 시퀀스

### 시퀀스의 특징
- 데이터를 순서대로 하나씩 나열하여 나타낸 데이터 구조
- 특정 위치(~번째)의 데이터를 가리킬 수 있다.
- 파이썬은 list, tuple, range, string 등 여러가지 시퀀스 collection 제공

## NLP를 3D 텐서로
1. 훈련 데이터: [[나는 사과를 좋아해], [나는 바나나를 좋아해], [나는 사과를 싫어해], [나는 바나나를 싫어해]]  

2. 컴퓨터의 입력으로 사용하기 위해 단어별로 나누기: [['나는', '사과를', '좋아해'], ['나는', '바나나를', '좋아해'], ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']]  
 ==> (4x3의 2D 텐서)  
 
3. 각 단어를 벡터로 만들기:  
(아래와 같이 단어를 3차원 벡터로 변환했다고 하겠다.)  
'나는' = [0.1, 0.2, 0.9]  
'사과를' = [0.3, 0.5, 0.1]  
'바나나를' = [0.3, 0.5, 0.2]  
'좋아해' = [0.7, 0.6, 0.5]  
'싫어해' = [0.5, 0.6, 0.7]  
(재구성)  
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]  
 ==> (4x3x3의 3D 텐서)

In [1]:
import numpy as np
import torch

## Numpy Review

In [2]:
# 1D Array With Numpy
t=np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ',t.shape)

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)


In [3]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


In [4]:
# 2D Array With Numpy
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t:  2
Shape of t:  (4, 3)


## PyTorch is like Numpy (but better)

### torch.Tensor
- multi-demensional matrix of a single data type.
- 10 tensor types
- torch.FloatTensor, DoubleTensor, ByteTensor, CharTensor, ShortTensor, IntTensor, LongTensor, BoolTensor ...


In [5]:
# 1D Array With PyTorch
t=torch.Tensor([0.,1.,2.,3.,4.,5.,6.])
print(t)
print(t.dim()) #rank
print(t.shape) #shape
print(t.size()) #shape
print(t[0],t[1],t[-1]) #Element
print(t[2:5],t[4:-1]) #Slicing
print(t[:2],t[3:]) #Slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [6]:
# 2D Array With PyTorch
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)
print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [7]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [8]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4)

4
torch.Size([1, 2, 3, 4])


## Frequently Used Operations in PyTorch  


### Mul vs Matmul

In [9]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Broadcasting

In [10]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [11]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [12]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Mean

In [13]:
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [14]:
# Can't use mean() on integers
t=torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [15]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [16]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax
- t.max(): 전체 텐서 데이터 중 최대 값만 인출
- t.max(dim=0): 특정 차원단위 최대값(max)와 최대값을 갖는 데이터 인덱스 인출
- 차원을 지정하면 두개의 데이터를 뽑을 수 있다. t.max(dim=0)[0]이 최대값(max)를 나타내고 t.max(dim=0)[1]이 최대값을 갖는 데이터 인덱스를 나타내게 된다.

In [18]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [19]:
print(t.max()) # Returns one value: max

tensor(4.)


In [20]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [21]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View
- 원소의 수를 유지하면서 텐서의 크기 변경, 매우 중요!!
- 넘파이에서의 reshape

In [22]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [23]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [24]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze
- 1인 차원을 제거한다.

In [25]:
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [26]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze
- 특정 위치에 1인 차원을 추가한다.

In [27]:
ft=torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [28]:
# 0은 첫 번재 차원
# 첫 번째 차원에 1인 차원을 추가하겠다.
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [29]:
#위의 결과가 view를 이용한 결과와 같다.
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [30]:
#두 번재 차원에 1인 차원을 추가하겠다.
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [31]:
#마지막 차원(여기서는 두 번째)에 1인 차원을 추가하겠다.
# 현재 크기는 (3,) 었으므로 마지막 차원에 1인 차원 추가하면 (3,1)
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [32]:
print(ft.unsqueeze(2))
print(ft.unsqueeze(2).shape)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### Scatter (for one-hot encoding)

In [33]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [34]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Casting

In [35]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [36]:
# Float 형으로 casting
print(lt.float())

tensor([1., 2., 3., 4.])


In [37]:
bt=torch.ByteTensor([True, False, False, True]) #bool형을 byte로 casting
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [38]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation
- 두 텐서 연결
- 연결 방법: 어느 차원을 늘릴 것인지 인자로 줄 수 있다.
- dim=0은 첫 번째 차원을 늘리라는 의미
- dim=1은 두 번째 차원을 늘리라는 의미
- 딥 러닝에서는 주로 모델의 입력 또는 중간 연산에서 두 개의 텐서를 연결하는 경우가 많습니다. 두 텐서를 연결해서 입력으로 사용하는 것은 두 가지의 정보를 모두 사용한다는 의미를 가지고 있습니다.

In [39]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [40]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking
- 연결(concatenate)을 하는 또 다른 방법
- 스택킹이 많은 연산을 포함하고 있어서 연결하는 것보다 더 편리할 때가 있다.

In [41]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [42]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=0))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [43]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like
- 1로 채워진 텐서와 0으로 채워진 텐서 

In [44]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [45]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation
- 덮어쓰기 연산

In [46]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [47]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Zip

In [48]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [49]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
